[workspace]
members = [
    "crates/core",
    "crates/ui",
    "crates/app",
    "crates/providers",
]
resolver = "2"

[workspace.package]
version      = "0.1.1"
authors      = ["Alex Joedt"]
edition      = "2021"
rust-version = "1.86.0"
repository   = "https://github.com/alexjoedt/numbr"
homepage     = "https://github.com/alexjoedt/numbr"
readme       = "README.md"
license      = "MIT OR Apache-2.0"
keywords     = ["calculator", "wayland", "hyprland", "modbus", "units"]
categories   = ["command-line-utilities", "mathematics"]

[workspace.dependencies]
thiserror    = "2"
rust_decimal = { version = "1", features = ["maths"] }
logos        = "0.14"
insta        = { version = "1", features = ["ron"] }
chrono       = { version = "0.4", default-features = false, features = ["std", "clock"] }
serde        = { version = "1", features = ["derive"] }
iced         = { version = "0.13", features = ["advanced", "multi-window"] }
tracing             = "0.1"
tracing-subscriber  = { version = "0.3", features = ["env-filter"] }

[workspace.lints.clippy]
all = "warn"
