[package]
name        = "numbr-ui"
description = "iced-based GUI for the numbr calculator"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
repository.workspace   = true
homepage.workspace     = true
readme.workspace       = true
license.workspace      = true
keywords.workspace     = true
categories.workspace   = true
authors.workspace      = true

[lints]
workspace = true

[dependencies]
numbr-core = { path = "../core" }
iced       = { workspace = true }
serde      = { workspace = true }
toml       = "1.1"
async-io   = "2"
blocking   = "1"
tracing    = { workspace = true }
