[package]
name        = "numbr"
description = "Natural-language calculator for Linux/Wayland, optimized for Hyprland"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
repository.workspace   = true
homepage.workspace     = true
readme.workspace       = true
license.workspace      = true
keywords.workspace     = true
categories.workspace   = true
authors.workspace      = true

[lints]
workspace = true

[[bin]]
name = "numbr"
path = "src/main.rs"

[dependencies]
numbr-ui            = { path = "../ui" }
numbr-core          = { path = "../core" }
tracing-subscriber  = { workspace = true }
